### ISSUE TITLE
Update to support CUDA 6 & 7

### ISSUE THREAD

**Issue by scottgs** [scottgs/cvtile#2]
Autotools elements need to be updated to support CUDA SDK / Toolkit versions 6.+ and 7.+

**Comment by ghost** [comment]
CUDA 7.0 Toolkit works fine locally for me.

**Comment by nivintw** [comment]
CUDA 7.0 is working on remote build server as of today.

**Comment by interputed** [comment]
I assume that since it supports cuda 8, this can be closed?
