### ISSUE TITLE
Fix SRS9 Build Dependencies

### ISSUE THREAD

**Issue by ghost** [scottgs/cvtile#5]
In order for users of the library to build, the gdal-exit library should be merged in or eliminated.

**Comment by scottgs** [comment]
Can I get an accounting of the dependencies (files / functions).  Thanks!

**Comment by ghost** [comment]
I'm already working on it. Libtool on Mac is failing in the GPU code. Working on that as we speak.

**Comment by ghost** [comment]
Works on OS-X albeit not without some serious hassle. The main issues revolve around the system installed libtool however, and can be avoided by detecting glibtool and using that instead. The buildDummy.cpp file is needed until we have an actual file to archive to stop newer versions of libtool from exploding when asked to make an empty archive.
